kind: Service
apiVersion: v1
metadata:
  name: teslaserver-service
spec:
  selector:
    app: tesla
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-teslaserver
  labels:
    app: tesla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesla
  template:
    metadata:
      labels:
        app: tesla
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: tesla
          image: example-teslaserver:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080