stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: adoptopenjdk/maven-openjdk11
          shellScript: |-
            mvn clean install
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml