stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: adoptopenjdk/maven-openjdk11
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./.Dockerfile
          buildContext: .
          tag: example-teslaserver:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./.deployment.yaml